### ISSUE TITLE
pip install -r requirements.txt fails on windows machine

### ISSUE THREAD

**Issue by odonnell-anthony** [AutomationPanda/device-registry-fastapi#1]
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\anthony.o'donnell\AppData\Local\Temp\pip-install-lllpzr6n\uvloop_d4ed1f7453a94e02bf307e2a897be071\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

**Comment by AutomationPanda** [comment]
Oh jeez. Thanks for letting me know. I'll investigate.

**Comment by AutomationPanda** [comment]
It appears that installing `uvicorn` brings in different dependencies between macOS and Windows.

I updated `requirements.txt` to have the minimal set of packages to run the app. These will bring in other dependencies automatically. I tested this new set on macOS and Windows, and I was able to successfully install all required packages and run the app.

@odonnell-anthony, please try again with the updates.
